from pathlib import Path
from functions.helper import run_process, failure
from functions.config import TIMEOUT_SECONDS, MCP_SECURITY_SCAN_CATEGORIES
import os
import json
import subprocess
import signal


def _kill_server_processes(server_command: str):
    """Kill any lingering MCP server processes spawned by mcp-scan.

    After mcp-scan finishes, the server process (node/python/go) may still
    be running. This function finds and kills processes whose command line
    matches the FULL server command used during the scan.

    IMPORTANT: Never pkill on short/generic terms like "run", "server.py",
    "index.js" etc. as they can match and kill the runner script itself.
    Always use the full server_command as the search pattern.
    """
    if not server_command:
        return

    killed = 0

    if os.name == "nt":
        # Windows: use WMIC with the full command to avoid false matches
        try:
            term_normalized = server_command.replace("/", "\\")
            result = subprocess.run(
                ["wmic", "process", "where",
                 f"CommandLine like '%{term_normalized}%'",
                 "get", "ProcessId"],
                capture_output=True, text=True, timeout=10
            )
            if result.returncode == 0:
                for line in result.stdout.strip().split("\n"):
                    line = line.strip()
                    if line.isdigit():
                        pid = int(line)
                        try:
                            subprocess.run(
                                ["taskkill", "/F", "/T", "/PID", str(pid)],
                                stdout=subprocess.DEVNULL,
                                stderr=subprocess.DEVNULL,
                                timeout=5
                            )
                            killed += 1
                        except Exception:
                            pass
        except Exception:
            pass
    else:
        # Linux/macOS: use pgrep to find PIDs matching the full command,
        # then kill only those PIDs (avoids killing our own runner script)
        try:
            result = subprocess.run(
                ["pgrep", "-f", server_command],
                capture_output=True, text=True, timeout=5
            )
            if result.returncode == 0 and result.stdout.strip():
                for pid_str in result.stdout.strip().split("\n"):
                    try:
                        pid = int(pid_str.strip())
                        # Safety: check cmdline doesn't contain our runner scripts
                        ps_result = subprocess.run(
                            ["ps", "-p", str(pid), "-o", "args="],
                            capture_output=True, text=True, timeout=5
                        )
                        cmdline = ps_result.stdout.strip()
                        if any(s in cmdline for s in [
                            "run_security_scan", "run_guard", "run_scan",
                            "run_check", "run_shield", "run_watch",
                            "run_fuzzing", "run_scanorama", "run_validator"
                        ]):
                            continue
                        os.kill(pid, 9)
                        killed += 1
                    except (ValueError, ProcessLookupError, PermissionError):
                        pass
        except Exception:
            pass

        # Also kill any mcp-scan processes that may be lingering
        try:
            subprocess.run(
                ["pkill", "-f", "mcp-scan scan"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=5
            )
        except Exception:
            pass

    if killed > 0:
        print(f"  Killed {killed} lingering server process(es)")


def parse_mcp_security_scan(json_path: Path) -> dict:
    """Parse the JSON report generated by mcp-scan."""
    if not json_path.exists():
        return None
    
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    findings = data.get("findings", [])
    
    categories = {}
    categories_passed = {}
    severity_counts = {}
    passed_count = 0
    failed_count = 0
    failed_findings_list = []

    for finding in findings:
        finding_id = finding.get("id", "")
        passed = finding.get("passed", True)
        severity = finding.get("severity", "info").lower()

        # Map finding ID to category name
        category_name = MCP_SECURITY_SCAN_CATEGORIES.get(finding_id, "unknown")

        if passed:
            passed_count += 1
            categories_passed[category_name] = categories_passed.get(category_name, 0) + 1
        else:
            failed_count += 1
            # Only count failed findings as vulnerabilities
            categories[category_name] = categories.get(category_name, 0) + 1
            severity_counts[severity] = severity_counts.get(severity, 0) + 1
            
            failed_findings_list.append({
                "id": finding_id,
                "category": category_name,
                "severity": severity,
                "title": finding.get("title", ""),
                "details": finding.get("details", ""),
                "remediation": finding.get("remediation", []),
                "references": finding.get("references", [])
            })

    total_findings = len(findings)
    total_vulnerabilities = failed_count

    # Calculate percentage of vulnerability per category
    percentage_of_vulnerability = {}
    if total_vulnerabilities > 0:
        for cat, count in categories.items():
            percentage_of_vulnerability[cat] = round((count / total_vulnerabilities) * 100, 2)

    # Calculate severity percentages
    percentage_of_severity = {}
    if total_vulnerabilities > 0:
        for sev, count in severity_counts.items():
            percentage_of_severity[sev] = round((count / total_vulnerabilities) * 100, 2)

    return {
        "mcp-security-scan": {
            "status": "completed",
            "total-vulnerabilities": total_vulnerabilities,
            "categories": categories,
            "categories_passed": categories_passed,
            "percentage_of_vulnerability": percentage_of_vulnerability,
            "findings": {
                "total": total_findings,
                "passed": passed_count,
                "failed": failed_count,
                "percentage_passed": round((passed_count / total_findings) * 100, 2) if total_findings > 0 else 0.0
            },
            "severity": {
                "counts": severity_counts,
                "percentage_of_severity": percentage_of_severity
            },
            "failed_findings": failed_findings_list
        }
    }

def execute_mcp_security_scan(repo_path: Path, command: str, main_file: str | list):
    """Execute mcp-scan security scanner via subprocess."""
    env = dict(os.environ)
    env["PYTHONIOENCODING"] = "utf-8"
    env["PYTHONUTF8"] = "1"

    main_file_str = " ".join(main_file) if isinstance(main_file, list) else str(main_file)

    # Build the full command for the MCP server
    if command == "node":
        server_command = f"node {main_file_str}"
    elif command == "python":
        server_command = f"python {main_file_str}"
    else:
        server_command = f"{command} {main_file_str}"

    # Output file path
    output_file = repo_path / "security_report.json"

    try:
        # Build mcp-scan command
        cmd = [
            "mcp-scan",
            "scan",
            "--transport", "stdio",
            "--command", server_command,
            "--format", "json",
            "--output", str(output_file)
        ]

        stdout, stderr, elapsed, code = run_process(
            cmd=cmd,
            cwd=repo_path,
            timeout=TIMEOUT_SECONDS,
            framework_name="MCP Security Scan",
            env=env
        )
    except TimeoutError:
        # Kill any lingering server processes on timeout
        _kill_server_processes(server_command)
        return failure("mcp-security-scan")
    finally:
        # ALWAYS kill lingering server processes after scan completes
        # mcp-scan may leave the MCP server running (node/python/go)
        _kill_server_processes(server_command)

    # Check if output file was created
    if not output_file.exists():
        print(f"Security report not found at {output_file}")
        return failure("mcp-security-scan")

    # Parse the JSON report
    parsed = parse_mcp_security_scan(output_file)

    if parsed is None:
        return failure("mcp-security-scan")

    # If the only vulnerability found is 'initialization-error', skip the server
    fw_data = parsed.get("mcp-security-scan", {})
    categories = fw_data.get("categories", {})
    if "initialization-error" in categories and len(categories) == 1:
        print(f"  Only initialization-error found for {repo_path.name} - skipping")
        try:
            output_file.unlink()
        except Exception:
            pass
        return failure("mcp-security-scan")

    # Clean up the report file
    try:
        output_file.unlink()
    except Exception:
        pass

    return parsed, "completed"
