"""
Comprehensive High-Confidence Filter for MCP-Watch scan results.

Filters ALL 6 vulnerability categories, keeping only findings that are
likely REAL vulnerabilities and discarding the massive false-positive noise
generated by mcp-watch's regex-based SAST approach.

Categories covered:
  1. credential-leak      (HARDCODED_CREDENTIALS, PLAINTEXT_STORAGE, INSECURE_CREDENTIAL_PERMISSIONS)
  2. steganographic-attack (ANSI_ESCAPE_INJECTION, WHITESPACE_INJECTION)
  3. data-exfiltration     (DATA_EXFILTRATION, MAGIC_PARAMETER_INJECTION, UNUSED_SENSITIVE_PARAMETER)
  4. protocol-violation    (INSECURE_TRANSPORT, SESSION_ID_IN_URL)
  5. input-validation      (COMMAND_INJECTION_RISK, SSRF_VULNERABILITY, PATH_TRAVERSAL)
  6. (bonus) tool-poisoning, prompt-injection, toxic-flow — kept for reference

Usage:
  python filter_all_categories.py
  python filter_all_categories.py --input <base_dir> --output <output_dir>

Output:
  - Per-category filtered JSON files in each category's subfolder
  - Global summary stats JSON in the base directory
"""

import sys

if sys.stdout and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if sys.stderr and hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import json
import re
import math
import argparse
from pathlib import Path
from collections import defaultdict, Counter
from datetime import datetime, timezone


# ── Paths ────────────────────────────────────────────────────────────────

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_BASE = SCRIPT_DIR


# ═══════════════════════════════════════════════════════════════════════════
#  UTILITIES
# ═══════════════════════════════════════════════════════════════════════════

def shannon_entropy(s: str) -> float:
    """Calculate Shannon entropy of a string."""
    if not s:
        return 0.0
    freq = Counter(s)
    length = len(s)
    return -sum((count / length) * math.log2(count / length) for count in freq.values())


def is_valid_finding(finding: dict) -> bool:
    """Check that a finding has a valid ID (not corrupted evidence leaked into id)."""
    vid = finding.get("id", "")
    return isinstance(vid, str) and len(vid) < 50 and vid.isupper() and "_" in vid


# ═══════════════════════════════════════════════════════════════════════════
#  CATEGORY 1: CREDENTIAL-LEAK
# ═══════════════════════════════════════════════════════════════════════════

# Provider-specific patterns that almost certainly indicate real credentials
CREDENTIAL_PROVIDER_PATTERNS = [
    # AI / LLM
    (re.compile(r'sk-ant-api03-[a-zA-Z0-9\-_]{48,85}'),           "Anthropic API Key"),
    (re.compile(r'sk-proj-[a-zA-Z0-9\-_]{40,}'),                  "OpenAI Project Key"),
    (re.compile(r'sk-[a-zA-Z0-9]{40,60}'),                        "OpenAI Legacy Key"),
    (re.compile(r'sess-[a-zA-Z0-9]{40,}'),                        "OpenAI Session Key"),
    (re.compile(r'hf_[a-zA-Z0-9]{34,}'),                          "Hugging Face Token"),

    # Cloud Providers
    (re.compile(r'AKIA[A-Z0-9]{16}'),                              "AWS Access Key ID"),
    (re.compile(r'ASIA[A-Z0-9]{16}'),                              "AWS Temporary Key"),
    (re.compile(r'AIza[a-zA-Z0-9_\-]{35}'),                       "Google API Key"),
    (re.compile(r'ya29\.[a-zA-Z0-9_\-]{50,}'),                    "Google OAuth Token"),

    # Git / CI/CD
    (re.compile(r'ghp_[a-zA-Z0-9]{36}'),                          "GitHub PAT (classic)"),
    (re.compile(r'gho_[a-zA-Z0-9]{36}'),                          "GitHub OAuth Token"),
    (re.compile(r'ghu_[a-zA-Z0-9]{36}'),                          "GitHub User Token"),
    (re.compile(r'ghs_[a-zA-Z0-9]{36}'),                          "GitHub Server Token"),
    (re.compile(r'ghr_[a-zA-Z0-9]{36}'),                          "GitHub Refresh Token"),
    (re.compile(r'github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}'),   "GitHub PAT (fine-grained)"),
    (re.compile(r'glpat-[a-zA-Z0-9\-_]{20,}'),                    "GitLab PAT"),

    # Messaging / SaaS
    (re.compile(r'xoxb-[0-9]{10,}-[0-9A-Za-z\-]+'),               "Slack Bot Token"),
    (re.compile(r'xoxp-[0-9]{10,}-[0-9A-Za-z\-]+'),               "Slack User Token"),
    (re.compile(r'xoxs-[0-9]{10,}-[0-9A-Za-z\-]+'),               "Slack Session Token"),
    (re.compile(r'xapp-[0-9]-[A-Z0-9]+-[0-9]+-[a-zA-Z0-9]+'),    "Slack App Token"),

    # Payments
    (re.compile(r'sk_live_[a-zA-Z0-9]{24,}'),                     "Stripe Secret Key (live)"),
    (re.compile(r'sk_test_[a-zA-Z0-9]{24,}'),                     "Stripe Secret Key (test)"),
    (re.compile(r'pk_live_[a-zA-Z0-9]{24,}'),                     "Stripe Publishable (live)"),
    (re.compile(r'pk_test_[a-zA-Z0-9]{24,}'),                     "Stripe Publishable (test)"),
    (re.compile(r'rk_live_[a-zA-Z0-9]{24,}'),                     "Stripe Restricted Key"),
    (re.compile(r'whsec_[a-zA-Z0-9]{32,}'),                       "Stripe Webhook Secret"),

    # Email / Communication
    (re.compile(r'SG\.[a-zA-Z0-9_\-]{22,}\.[a-zA-Z0-9_\-]{43,}'), "SendGrid API Key"),
    (re.compile(r'SK[a-f0-9]{32}'),                                "Twilio API Key"),

    # Infrastructure / DevOps
    (re.compile(r'dckr_pat_[a-zA-Z0-9_\-]{24,}'),                 "Docker PAT"),
    (re.compile(r'npm_[a-zA-Z0-9]{36}'),                           "npm Token"),
    (re.compile(r'pypi-AgEIcH[a-zA-Z0-9\-_]{50,}'),               "PyPI API Token"),
    (re.compile(r'vercel_[a-zA-Z0-9]{24,}'),                       "Vercel API Token"),
    (re.compile(r'npl_[a-zA-Z0-9]{24,}'),                          "Netlify PAT"),
    (re.compile(r'sbp_[a-f0-9]{40}'),                              "Supabase Service Key"),

    # Databases (connection URIs with credentials)
    (re.compile(r"mongodb(?:\+srv)?://[^:]+:[^@]+@[^\s'\"<>]{5,}"), "MongoDB URI with creds"),
    (re.compile(r"postgres(?:ql)?://[^:]+:[^@]+@[^\s'\"<>]{5,}"),   "PostgreSQL URI with creds"),
    (re.compile(r"mysql://[^:]+:[^@]+@[^\s'\"<>]{5,}"),             "MySQL URI with creds"),
    (re.compile(r"redis://[^:]+:[^@]+@[^\s'\"<>]{5,}"),             "Redis URI with creds"),

    # Private Keys
    (re.compile(r'-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----'), "Private Key Header"),

    # JWT (only with 3 segments, each 10+ chars)
    (re.compile(r'eyJ[a-zA-Z0-9_-]{10,}\.eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_\-]{10,}'), "JWT Token"),

    # Generic high-confidence assignment (api_key = "longRandomValue")
    (re.compile(
        r'(?:api[_-]?key|api[_-]?secret|secret[_-]?key|auth[_-]?token|access[_-]?token)'
        r'\s*[:=]\s*["\']([a-zA-Z0-9\-_./+]{20,})["\']',
        re.IGNORECASE
    ), "Generic API Key Assignment"),
]

# Evidence patterns that are NEVER real credentials
CREDENTIAL_FALSE_POSITIVE_PATTERNS = [
    # Hashes / checksums
    re.compile(r'"(?:sha256?|sha384|sha512|md5|hash|checksum|digest|fileSha256|commit_sha|sha|etag)"'
               r'\s*:\s*"[a-fA-F0-9]{32,}"', re.IGNORECASE),
    re.compile(r'"(?:sha256?|sha384|sha512|md5|hash|checksum|digest|fileSha256|commit_sha|sha)"'
               r'\s*:\s*"', re.IGNORECASE),

    # Blockchain / Ethereum addresses
    re.compile(r'0x[a-fA-F0-9]{40}'),
    re.compile(r'"(?:address|source|from|to|contractAddress|sender|receiver|owner)"\s*:\s*"0x', re.IGNORECASE),

    # Google API discovery schema refs
    re.compile(r'"\$ref"\s*:\s*"Google[A-Z]'),
    re.compile(r'"id"\s*:\s*"Google(?:Cloud|Devtools|Iam|Api|Monitoring|Storage|Compute)', re.IGNORECASE),

    # Long CamelCase identifiers (class names, not secrets)
    re.compile(r'"[A-Z][a-zA-Z]{30,}"'),

    # __name() wrapper from bundled JS
    re.compile(r'__name\s*\('),

    # Example / placeholder credentials
    re.compile(r'(?:your[-_]?(?:api[-_]?key|token|secret)|example|demo|placeholder|'
               r'xxx{3,}|yyy{3,}|123456|abcdef{2,}|replace[-_]?me|change[-_]?me|'
               r'dummy|fake|mock|sample|insert[-_]?here|insert[-_]?your|'
               r'key[-_]?here|token[-_]?example|secret[-_]?placeholder|TODO|FIXME)',
               re.IGNORECASE),

    # AWS example keys
    re.compile(r'AKIAIOSFODNN7EXAMPLE'),

    # Template variables (not hardcoded)
    re.compile(r'\$\{[^}]+\}'),
    re.compile(r'\{\{[^}]+\}\}'),
    re.compile(r'<[A-Z_]{3,}>'),

    # Environment variable reads (not hardcoded)
    re.compile(r'process\.env\.\w+'),
    re.compile(r'os\.environ\b'),
    re.compile(r'os\.getenv\b'),

    # Pure hex strings in non-credential context (checksums, tx hashes)
    re.compile(r'^"?[a-fA-F0-9]{40,128}"?,?$'),

    # Base64 strings that are actually just long ASCII text
    re.compile(r'"[a-zA-Z]{40,}"'),  # All-alpha, no mixed case typical of secrets

    # Test file paths
    re.compile(r'(?:test|spec|mock|fixture|__test__|__mock__|\.test\.|\.spec\.)', re.IGNORECASE),
]


def filter_credential_finding(finding: dict) -> tuple[bool, str]:
    """
    Returns (keep, reason).
    For HARDCODED_CREDENTIALS: re-test evidence against provider-specific patterns.
    For PLAINTEXT_STORAGE / INSECURE_CREDENTIAL_PERMISSIONS: keep with lighter filter.
    """
    vid = finding.get("id", "")
    evidence = finding.get("evidence", "") or ""
    filepath = finding.get("file", "") or ""

    if vid == "HARDCODED_CREDENTIALS":
        # Filter out test files — credentials in tests are intentional fixtures
        if re.search(r'(?:test|spec|mock|fixture|__test__|__mock__|\.test\.|\.spec\.|/tests?/)', filepath, re.IGNORECASE):
            return False, "test_file"

        # Filter out third-party / vendored code (not the server's own code)
        if re.search(r'(?:node_modules|venv|\.venv|site-packages|vendor|dist|build|__pycache__|\.tox|\.eggs)', filepath, re.IGNORECASE):
            return False, "third_party_code"

        # Filter out JSON data files (openapi.json, config examples, etc.)
        if re.search(r'\.(?:json|yaml|yml)$', filepath, re.IGNORECASE):
            return False, "data_config_file"

        # Filter out documentation files
        if re.search(r'\.(?:md|rst|txt|html|htm)$', filepath, re.IGNORECASE):
            return False, "documentation_file"

        # Filter out docs/ directories (client-side search keys, etc.)
        if re.search(r'(?:^|/)docs?/', filepath, re.IGNORECASE):
            return False, "docs_directory"

        # Filter out well-known example JWTs (jwt.io default tokens)
        if re.search(r'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\.eyJzdWIiOiIxMjM0NTY3ODkw', evidence):
            return False, "jwt_io_example_token"

        # Filter out public/client-side API keys (analytics, search, Firebase)
        # These are DESIGNED to be embedded in frontend code, not secrets
        if re.search(
            r'(?:amplitude|analytics|telemetry|tracking|segment|mixpanel|'
            r'algolia|search[_-]?(?:key|api)|gtag|ga[_-]?(?:key|id|token)|'
            r'google[_-]?analytics|measurement[_-]?id)',
            evidence, re.IGNORECASE
        ):
            return False, "public_client_side_key"

        # Firebase API keys are public by design (used in frontend firebase config)
        if re.search(r'(?:firebase|FIREBASE)', evidence) and re.search(r'AIza', evidence):
            return False, "firebase_public_key"

        # First check if it's a known false positive pattern
        for fp_pattern in CREDENTIAL_FALSE_POSITIVE_PATTERNS:
            if fp_pattern.search(evidence):
                return False, "false_positive_pattern"

        # Then check if it matches a provider-specific pattern
        for pattern, provider in CREDENTIAL_PROVIDER_PATTERNS:
            if pattern.search(evidence):
                # Extra check: for Generic API Key Assignment, verify entropy
                if provider == "Generic API Key Assignment":
                    m = pattern.search(evidence)
                    if m and m.group(1):
                        ent = shannon_entropy(m.group(1))
                        if ent < 3.5:
                            return False, "low_entropy_generic"
                return True, f"provider:{provider}"

        # Didn't match any provider pattern = likely false positive from
        # the overly broad Base64-like or generic pattern in mcp-watch
        return False, "no_provider_match"

    elif vid == "PLAINTEXT_STORAGE":
        # This rule has 3 conditions already (write + credential keyword + no encryption)
        # Still produces FPs with logging/debug writes. Filter out:

        # Filter out third-party / vendored code
        if re.search(r'(?:node_modules|venv|\.venv|site-packages|vendor|dist|build|__pycache__)', filepath, re.IGNORECASE):
            return False, "third_party_code"

        # Filter out documentation files
        if re.search(r'\.(?:md|rst|txt|html|htm)$', filepath, re.IGNORECASE):
            return False, "documentation_file"

        # Filter out docs/ directories
        if re.search(r'(?:^|/)docs?/', filepath, re.IGNORECASE):
            return False, "docs_directory"

        # Filter out test files
        if re.search(r'(?:test|spec|mock|fixture|__test__|\.test\.|\.spec\.|/tests?/)', filepath, re.IGNORECASE):
            return False, "test_file"

        fp_indicators = [
            r'sys\.stderr\.write',
            r'console\.',
            r'log\(',
            r'logger\.',
            r'logging\.',
            r'debug\(',
            r'print\(',
            r'\.write\s*\(\s*["\']',  # Writing string literals, not variables with secrets
            r'stderr',
            r'keyboard\.write',       # HID/keyboard, not credential storage
            r'f\.write\s*\(\s*f"',    # f-string write (benchmark, report, etc.)
            r'\.writeFile\s*\(',      # Node writeFile with hardcoded content
        ]
        for pattern in fp_indicators:
            if re.search(pattern, evidence, re.IGNORECASE):
                return False, "logging_not_storage"

        # The "write" must be writing an actual credential variable, not just any data
        has_credential_var = bool(re.search(
            r'(?:password|passwd|secret|token|api_key|apikey|credentials?|private_key)\b',
            evidence, re.IGNORECASE
        ))
        if not has_credential_var:
            return False, "write_without_credential_variable"

        return True, "plaintext_storage_confirmed"

    elif vid == "INSECURE_CREDENTIAL_PERMISSIONS":
        # Already quite specific (chmod + credential keyword), keep
        # But filter out docs/test files
        if re.search(r'\.(?:md|rst|txt|html|htm)$', filepath, re.IGNORECASE):
            return False, "documentation_file"
        if re.search(r'(?:^|/)docs?/', filepath, re.IGNORECASE):
            return False, "docs_directory"
        if re.search(r'(?:test|spec|mock|fixture|/tests?/)', filepath, re.IGNORECASE):
            return False, "test_file"
        return True, "insecure_perms_confirmed"

    return False, "unknown_id"


# ═══════════════════════════════════════════════════════════════════════════
#  CATEGORY 2: STEGANOGRAPHIC-ATTACK
# ═══════════════════════════════════════════════════════════════════════════

# ANSI escape codes used purely for console coloring (not hiding text)
SAFE_ANSI_CODES = re.compile(
    r'\\x1b\[(?:'
    r'0m|'           # reset
    r'1m|'           # bold
    r'2m|'           # dim
    r'3m|'           # italic
    r'4m|'           # underline
    r'[34][0-7]m|'   # foreground/background colors (30-37, 40-47)
    r'9[0-7]m|'      # bright foreground colors
    r'10[0-7]m'      # bright background colors
    r')$'
)

# DANGEROUS ANSI: screen manipulation, cursor hiding, text hiding
DANGEROUS_ANSI = re.compile(
    r'\\x1b\[(?:'
    r'2J|'           # clear screen
    r'[12]K|'        # clear line
    r'8m|'           # hidden text
    r'\?25[lh]|'     # cursor show/hide
    r'[0-9]+[AB]|'   # cursor up/down
    r'[0-9]+;[0-9]+H'  # cursor position
    r')'
)


def filter_steganographic_finding(finding: dict) -> tuple[bool, str]:
    """Filter steganographic attack findings."""
    vid = finding.get("id", "")
    evidence = finding.get("evidence", "") or ""

    if vid == "ANSI_ESCAPE_INJECTION":
        filepath = finding.get("file", "")

        # Filter out test files
        if re.search(r'(?:test|spec|mock|fixture|__test__|\.test\.|\.spec\.|/tests?/)', filepath, re.IGNORECASE):
            return False, "test_file"

        # Filter out third-party / vendored code
        if re.search(r'(?:node_modules|venv|\.venv|site-packages|vendor|dist|build)', filepath, re.IGNORECASE):
            return False, "third_party_code"

        # Check if it's in a file that's clearly a CLI color utility
        color_file_indicators = [
            "color", "chalk", "ansi", "terminal", "console", "cli",
            "logger", "log", "output", "format", "style", "theme",
            "pretty", "print", "display", "render"
        ]
        is_color_utility = any(ind in filepath.lower() for ind in color_file_indicators)

        # Check if evidence contains ONLY safe coloring codes
        # Extract all ANSI codes from evidence
        all_ansi = re.findall(r'\\x1b\[[0-9;]*[a-zA-Z]', evidence)
        all_ansi += re.findall(r'\\u001b\[[0-9;]*[a-zA-Z]', evidence)

        has_dangerous = DANGEROUS_ANSI.search(evidence)

        if has_dangerous:
            # If dangerous ANSI is in a tool description -> very suspicious
            if "description" in evidence.lower():
                return True, "dangerous_ansi_in_description"
            return True, "dangerous_ansi_codes"

        # ALL standard coloring codes are safe — reject them all.
        # This covers: [0m reset, [1m bold, [2-4m dim/italic/underline,
        # [30-37m] [40-47m] [90-97m] [100-107m] foreground/background colors
        # If no dangerous code found, it's just coloring.
        return False, "safe_coloring_code"

    elif vid == "WHITESPACE_INJECTION":
        filepath = finding.get("file", "")

        # Filter out test files
        if re.search(r'(?:test|spec|mock|fixture|__test__|\.test\.|\.spec\.|/tests?/)', filepath, re.IGNORECASE):
            return False, "test_file"

        # Filter out third-party code
        if re.search(r'(?:node_modules|venv|\.venv|site-packages|vendor|dist|build)', filepath, re.IGNORECASE):
            return False, "third_party_code"

        # Most whitespace findings are just poorly formatted code
        # Only keep if whitespace is extreme (>200 chars) or in description/tool context
        ws_match = re.search(r'Line contains (\d+) whitespace', evidence)
        ws_count = int(ws_match.group(1)) if ws_match else 0

        if ws_count > 200:
            return True, f"extreme_whitespace_{ws_count}"

        # Check if it's in a tool description or schema
        content_part = evidence.split('": "', 1)[-1] if '": "' in evidence else evidence
        if any(kw in evidence.lower() for kw in ["description", "schema", "tool", "prompt"]):
            return True, "whitespace_in_tool_definition"

        return False, "normal_indentation"

    return False, "unknown_id"


# ═══════════════════════════════════════════════════════════════════════════
#  CATEGORY 3: DATA-EXFILTRATION
# ═══════════════════════════════════════════════════════════════════════════

# Magic parameters that are ACTUALLY used legitimately in many codebases
LEGITIMATE_MAGIC_PARAM_CONTEXTS = [
    # model_name is the most common false positive — used everywhere legitimately
    re.compile(r'def\s+\w*(?:test|mock|setup|create|init|build|get|set|format|validate|parse|config|load|save|register|log|display|show|render|generate_model|list_model|select_model|check_model)\w*\s*\(', re.IGNORECASE),
    # system_prompt used in legitimate prompt management
    re.compile(r'def\s+\w*(?:save|load|get|set|update|delete|create|format|validate|parse|render|display)_?system_?prompt\w*\s*\(', re.IGNORECASE),
    # Test files
    re.compile(r'(?:test_|_test\.py|\.test\.|\.spec\.|__test__|mock_|fixture)', re.IGNORECASE),
]


def filter_data_exfiltration_finding(finding: dict) -> tuple[bool, str]:
    """Filter data exfiltration findings."""
    vid = finding.get("id", "")
    evidence = finding.get("evidence", "") or ""
    filepath = finding.get("file", "") or ""

    if vid == "DATA_EXFILTRATION":
        # The json.dumps pattern is the biggest FP source — it flags ANY json.dumps
        # that mentions "prompt", "context", "tool", "history", "conversation"
        # But these words appear in legitimate data serialization constantly

        # Filter out third-party / vendored code
        if re.search(r'(?:node_modules|venv|\.venv|site-packages|vendor|dist|build)', filepath, re.IGNORECASE):
            return False, "third_party_code"

        # Filter out test files
        if re.search(r'(?:test|spec|mock|fixture|__test__|\.test\.|\.spec\.|/tests?/)', filepath, re.IGNORECASE):
            return False, "test_file"

        # Keep only if there's BOTH an HTTP outbound AND sensitive data keyword
        has_http_outbound = bool(re.search(
            r'(?:requests\.(?:post|put|patch)|fetch\s*\(|axios\.(?:post|put|patch)|'
            r'urllib\.request|http\.request)',
            evidence, re.IGNORECASE
        ))

        has_sensitive_data = bool(re.search(
            r'(?:conversation_history|system_prompt|chain_of_thought|'
            r'tool_call_history|session_data|internal_state)',
            evidence, re.IGNORECASE
        ))

        # json.dumps alone is NOT exfiltration — it's just serialization
        is_just_json_dumps = bool(re.search(r'^[^)]*json\.dumps?\s*\(', evidence))
        if is_just_json_dumps and not has_http_outbound:
            return False, "json_serialization_not_exfiltration"

        # base64.encode of sensitive data is suspicious even without HTTP
        has_encoding_of_sensitive = bool(re.search(
            r'base64\.(?:encode|b64encode)\s*\([^)]*(?:conversation|history|prompt|system)',
            evidence, re.IGNORECASE
        ))

        # system_prompt alone is NOT exfiltration — it's used in every LLM wrapper
        # Only keep if it's combined with an HTTP outbound or encoding
        is_system_prompt_only = bool(re.search(r'\bsystem_prompt\b', evidence)) and not bool(re.search(
            r'\b(?:conversation_history|tool_call_history|chain_of_thought|session_data|internal_state)\b',
            evidence
        ))

        # system_prompt in __init__, constructor, class definition, property, setter/getter
        if is_system_prompt_only and re.search(
            r'(?:def\s+__init__|def\s+(?:get|set|update|create|format|build|load|save|validate|parse|render)\w*\s*\(|'
            r'self\.system_prompt|this\.system_prompt|'
            r'class\s+\w+|constructor\s*\(|'
            r'system_prompt\s*[:=]\s*(?:str|string|None|null|""|\'\'|\[\]|Optional))',
            evidence, re.IGNORECASE
        ):
            return False, "system_prompt_in_constructor_or_setter"

        # system_prompt used in LLM call construction (generate, query, chat, complete, invoke)
        if is_system_prompt_only and re.search(
            r'(?:generate|query|chat|complete|invoke|call|send|create_message|_query_model|ask|run)\s*\(',
            evidence, re.IGNORECASE
        ):
            return False, "system_prompt_in_llm_call"

        if has_http_outbound and has_sensitive_data:
            return True, "http_exfiltration_of_sensitive_data"
        if has_encoding_of_sensitive:
            return True, "base64_encoding_of_sensitive_data"

        # HTTP outbound with generic keywords like "prompt", "tool" in the URL
        # is almost always a legitimate API call (e.g. /mcp/v1/tools/scan, PROMPT_GUARD_URL)
        # Only flag if the sensitive data keyword is in the PAYLOAD, not in the URL path
        if has_http_outbound:
            # Check if the keyword is in a variable being sent, not in the URL itself
            has_sensitive_in_payload = bool(re.search(
                r'(?:data|body|payload|json)\s*[:=]\s*.*(?:conversation|history|prompt|context)',
                evidence, re.IGNORECASE
            ))
            if has_sensitive_in_payload:
                # Exclude calls to security/guard/redaction services — they NEED the prompt to scan it
                if re.search(
                    r'(?:guard|redact|sanitize|filter|moderate|scan|check|validate|shield|safety|content.?policy|classify|virus.?total)',
                    evidence, re.IGNORECASE
                ):
                    return False, "security_service_call"
                # Exclude plugin/hook methods that just have 'payload' as a parameter name
                if re.search(r'(?:def|async def)\s+\w+\s*\(self,\s*payload\b', evidence):
                    return False, "plugin_hook_method"
                return True, "http_exfiltration_payload"
            return False, "http_call_keyword_in_url_only"

        # system_prompt without any outbound mechanism — just prompt handling code
        if is_system_prompt_only:
            return False, "system_prompt_without_exfiltration"

        return False, "no_exfiltration_pattern"

    elif vid == "MAGIC_PARAMETER_INJECTION":
        # Filter out third-party code
        if re.search(r'(?:node_modules|venv|\.venv|site-packages|vendor|dist|build)', filepath, re.IGNORECASE):
            return False, "third_party_code"

        # model_name is the #1 false positive — it's used in virtually every ML codebase
        # for legitimate model selection, not for magic parameter attacks
        if re.search(r'\bmodel_name\b', evidence) and not re.search(
            r'\b(?:conversation_history|tool_call_history|system_prompt|'
            r'chain_of_thought|every_single_previous_tool_call|all_tool_calls|'
            r'full_context|session_data|internal_state|debug_info)\b',
            evidence
        ):
            return False, "model_name_is_legitimate"

        # system_prompt in a function that manages prompts is legitimate
        if re.search(r'def\s+\w*(?:save|load|get|set|update|format|parse|render)_?\w*system_?prompt', evidence, re.IGNORECASE):
            return False, "prompt_management_function"

        # debug_info as a parameter is common in legitimate debugging
        if re.search(r'\bdebug_info\b', evidence) and not re.search(
            r'\b(?:conversation_history|system_prompt|tool_call_history)\b', evidence
        ):
            return False, "legitimate_debug_param"

        # Test files
        if re.search(r'(?:test_|_test\.py|\.test\.|\.spec\.|__test__|mock_|fixture|e2e)', filepath, re.IGNORECASE):
            return False, "test_file"

        # Magic parameter injection is about hidden params in TOOL DEFINITIONS (inputSchema)
        # that trick the LLM into sending data. Regular function parameters in code are NOT attacks.
        # Only flag if the parameter appears in a tool schema/definition context.
        truly_magic = [
            'conversation_history', 'tool_call_history', 'chain_of_thought',
            'every_single_previous_tool_call', 'all_tool_calls', 'full_context',
            'internal_state', 'tools_list'
        ]

        is_tool_schema = bool(re.search(
            r'(?:inputSchema|"properties"|"parameters"\s*:\s*\{|tool.*description|'
            r'register.*tool|add_tool|create_tool|Tool\s*\(|\.tool\s*\()',
            evidence, re.IGNORECASE
        ))

        for param in truly_magic:
            if param in evidence.lower().replace("-", "_").replace(" ", "_"):
                if is_tool_schema:
                    return True, f"magic_param_in_schema:{param}"
                # Regular function parameter — not an attack
                if re.search(r'(?:def\s+\w+\s*\(|async\s+def\s+\w+\s*\(|function\s+\w+\s*\()', evidence):
                    return False, f"regular_function_param:{param}"
                return True, f"magic_param:{param}"

        # system_prompt: only flag if it's in a TOOL DEFINITION (inputSchema, description)
        # NOT as a regular function parameter or method — it's used in every LLM wrapper
        if 'system_prompt' in evidence:
            # In a tool schema or description → suspicious (magic param attack)
            if re.search(r'(?:inputSchema|"properties"|"parameters"|tool.*description)', evidence, re.IGNORECASE):
                return True, "magic_param:system_prompt_in_tool_schema"
            # Regular function parameter, method, property → legitimate
            return False, "system_prompt_legitimate_usage"

        return False, "benign_parameter"

    elif vid == "UNUSED_SENSITIVE_PARAMETER":
        # This rule defaults to flagging when it can't find the function body
        # (which happens very often). Very high FP rate.
        # Only keep if the parameter is one of the truly dangerous magic params
        truly_magic = [
            'conversation_history', 'tool_call_history', 'chain_of_thought',
            'every_single_previous_tool_call', 'all_tool_calls', 'full_context',
        ]
        for param in truly_magic:
            if param in evidence.lower().replace("-", "_"):
                return True, f"unused_magic:{param}"

        # model_name, system_prompt, debug_info — too many legitimate uses
        return False, "common_parameter_name"

    elif vid == "CONVERSATION_EXFILTRATION_TRIGGER":
        # Filter out third-party code
        if re.search(r'(?:node_modules|venv|\.venv|site-packages|vendor|dist|build)', filepath, re.IGNORECASE):
            return False, "third_party_code"

        # Filter out test files
        if re.search(r'(?:test|spec|mock|fixture|__test__|\.test\.|\.spec\.|/tests?/)', filepath, re.IGNORECASE):
            return False, "test_file"

        # Tool descriptions that mention "private message", "DM", "personal" are
        # legitimate messaging tools, not exfiltration
        if re.search(r'(?:send\s+a\s+(?:private|direct)\s+message|DM|one-on-one|personal\s+(?:message|chat))', evidence, re.IGNORECASE):
            return False, "legitimate_messaging_tool"

        # Check if "description" is really a tool description with exfiltration language
        has_send_forward = bool(re.search(
            r'(?:forward|exfiltrate|steal|extract|leak|transmit)',
            evidence, re.IGNORECASE
        ))
        has_conversation = bool(re.search(
            r'(?:conversation\s+history|chat\s+history|message\s+history|all\s+(?:messages|conversations))',
            evidence, re.IGNORECASE
        ))
        if has_send_forward and has_conversation:
            return True, "exfiltration_in_description"

        # "Get details of a specific conversation" is a legitimate tool description
        if re.search(r'(?:get|list|fetch|retrieve|search|view|show|display|read)\s+(?:details?|info|data|messages?)\s+(?:of|from|about|for)', evidence, re.IGNORECASE):
            return False, "legitimate_conversation_tool"

        # description just mentions "history" or "conversation" without exfiltration intent
        return False, "no_exfiltration_intent"

    return False, "unknown_id"


# ═══════════════════════════════════════════════════════════════════════════
#  CATEGORY 4: PROTOCOL-VIOLATION
# ═══════════════════════════════════════════════════════════════════════════

def filter_protocol_violation_finding(finding: dict) -> tuple[bool, str]:
    """Filter protocol violation findings."""
    vid = finding.get("id", "")
    evidence = finding.get("evidence", "") or ""
    filepath = finding.get("file", "") or ""

    if vid == "INSECURE_TRANSPORT":
        # Already filters localhost/127.0.0.1/example.com, but still noisy

        # Filter out package-lock.json, package.json, lockfiles (license URLs, not code)
        if re.search(r'(?:package-lock\.json|package\.json|yarn\.lock|pnpm-lock|Pipfile\.lock|poetry\.lock|composer\.lock)', filepath, re.IGNORECASE):
            return False, "lockfile_or_manifest"

        # Filter out ALL data/config files — not executable code.
        # http:// URLs in these are references (HL7 FHIR, SNOMED, schemas, configs),
        # not code that makes insecure HTTP connections.
        if re.search(r'\.(?:json|yaml|yml|toml|ini|cfg|env|xml)$', filepath, re.IGNORECASE):
            return False, "data_config_file"

        # Filter out third-party / vendored code
        if re.search(r'(?:node_modules|venv|\.venv|site-packages|vendor|dist|build)', filepath, re.IGNORECASE):
            return False, "third_party_code"

        # Filter out test files
        if re.search(r'(?:test|spec|mock|fixture|__test__|__mock__|\.test\.|\.spec\.|/tests?/)', filepath, re.IGNORECASE):
            return False, "test_file"

        # Filter out comments
        if re.match(r'^\s*(?://|#|\*|/\*)', evidence):
            return False, "comment"

        # Filter out documentation / markdown files
        if re.search(r'\.(?:md|rst|txt|html|htm)$', filepath, re.IGNORECASE):
            return False, "documentation_file"

        # Filter out docs/ directories
        if re.search(r'(?:^|/)docs?/', filepath, re.IGNORECASE):
            return False, "docs_directory"

        # Filter out README content in JSON
        if re.search(r'"(?:Readme|ReadmeCN|description|readme)"', evidence, re.IGNORECASE):
            return False, "readme_content"

        # Filter out URLs with template variables (Python f-strings, JS template literals, etc.)
        # Catches: http://{settings.host}, http://${HOST}, http://{{host}}, http://$HOST
        if re.search(r'http://[^"]*(?:\{[a-zA-Z_]|\$[a-zA-Z_{]|\{\{)', evidence):
            return False, "template_variable_url"

        # Filter out common safe HTTP URLs (schemas, specs, namespaces, registries)
        safe_urls = [
            r'http://www\.w3\.org',
            r'http://schemas?\.',
            r'http://xmlns\.',
            r'http://purl\.org',
            r'http://json-schema\.org',
            r'http://www\.apache\.org',
            r'http://maven\.',
            r'http://creativecommons\.org',
            r'http://(?:www\.)?example\.',
            r'http://[a-zA-Z0-9_-]+\.github\.io',  # GitHub Pages (docs/licenses)
            r'http://www\.opengis\.net',             # OGC namespaces
            r'http://www\.idpf\.org',                # EPUB spec
            r'http://www\.color\.org',               # ICC color profiles
            r'http://ns\.',                          # XML namespaces
            r'http://www\.openarchives\.org',         # OAI
            r'http://ogp\.me',                        # Open Graph Protocol
            r'http://www\.sitemaps\.org',              # Sitemaps
            r'http://www\.rssboard\.org',              # RSS
            r'http://purl\.oclc\.org',                 # Dublin Core
            r'http://dbpedia\.org',                    # DBpedia
            r'http://www\.w3\.org',                    # W3C (already there but being thorough)
            r'http://rdfs?\.',                         # RDF schemas
            r'http://xmlns\.com',                      # XML namespaces
        ]
        for pattern in safe_urls:
            if re.search(pattern, evidence, re.IGNORECASE):
                return False, "safe_schema_url"

        # Filter out config for local services (common in MCP servers)
        # Includes hostnames without dots (internal services like "teradata-mcp-server")
        if re.search(r'http://(?:0\.0\.0\.0|host|hostname|\$)', evidence):
            return False, "local_config_variable"

        # Filter out internal service URLs (no dot in hostname = not a public domain)
        url_match = re.search(r'http://([^/:"\s]+)', evidence)
        if url_match:
            hostname = url_match.group(1)
            if '.' not in hostname:
                return False, "internal_service_hostname"

        # Filter out license/spec URLs in non-JSON files too
        if re.search(r'(?:license|licence|spdx)', evidence, re.IGNORECASE):
            return False, "license_url"

        # Filter out XML namespaces: {http://...} or xmlns="http://..."
        if re.search(r'(?:\{http://|xmlns\s*=\s*["\']http://)', evidence):
            return False, "xml_namespace"

        # Filter out URL validation / checking code (string literal used to test against)
        # e.g.: startsWith("http://"), .includes("http://"), === "http://", url.match("http://")
        if re.search(r'(?:startsWith|endsWith|includes|indexOf|match|test|search|replace|split)\s*\(\s*["\']http://', evidence):
            return False, "url_validation_code"

        # Filter out error messages / validation messages about URLs
        # e.g.: "must start with http://", "URL must be a valid URL starting with http://"
        if re.search(r'(?:must\s+(?:start|begin)|starting\s+with|invalid|expected|should\s+(?:start|begin)|format)\s*.*http://', evidence, re.IGNORECASE):
            return False, "url_validation_message"

        # Filter out console.error / console.log messages containing http://
        if re.search(r'console\.(?:error|warn|log|info)\s*\(.*http://', evidence):
            return False, "console_log_message"

        # Filter out string comparison / assignment of bare "http://" literal
        # e.g.: protocol === "http://", scheme = "http://", "must start with http://"
        if re.search(r'(?:["\']http://["\']|["\']https?://["\'])', evidence):
            return False, "protocol_string_literal"

        # Filter out SPARQL/RDF prefixes: PREFIX xxx: <http://...>
        if re.search(r'(?:PREFIX\s+\w*:\s*<http://|@prefix\s+)', evidence, re.IGNORECASE):
            return False, "sparql_rdf_prefix"

        # Filter out bundled/minified JS assets
        if re.search(r'(?:bundle|\.min\.|dist/|assets/scripts/|vendor\.)', filepath, re.IGNORECASE):
            return False, "bundled_js_asset"

        # Filter out description strings containing http:// links (documentation, not code)
        if re.search(r'(?:"description"|"summary"|"help"|"info"|"readme"|"text"|"message"|"detail"|"comment")\s*[:=]', evidence, re.IGNORECASE):
            return False, "description_string_with_link"

        # Filter out Python description= / help= keyword args with URLs
        if re.search(r'(?:description|help|message|detail|label|title|placeholder)\s*=\s*["\'].*http://', evidence, re.IGNORECASE):
            return False, "description_kwarg_with_link"

        # Filter out string concatenation/interpolation building URLs from variables
        # e.g.: `http://${host}:${port}`, "http://" + host
        if re.search(r'http://["\']?\s*\+\s*\w|http://\$\{|http://["\']?\s*\.\s*concat', evidence):
            return False, "dynamic_url_construction"

        # Filter out dictionary/object literal values — data, not HTTP connections
        # e.g.: 'source': 'http://...', "website": "http://...", "/RegistryName": "http://..."
        if re.search(r'["\'][^"\']*["\']\s*:\s*["\']http://', evidence):
            return False, "dict_value_not_connection"

        # Filter out http:// URLs used as dictionary KEYS (namespace maps, etc.)
        # e.g.: "http://www.opengis.net/wfs/2.0": {
        if re.search(r'["\']http://[^"\']+["\']\s*:', evidence):
            return False, "url_as_dict_key"

        # Filter out hardcoded URL strings assigned to variables or returned (reference data)
        # e.g.: return 'http://ws.audioscrobbler.com', BASE_URL = "http://..."
        if re.search(r'(?:return\s+|=\s*)["\']http://[^"\']+["\']', evidence):
            # Only keep if it's clearly making a connection (fetch, request, etc.)
            if not re.search(r'(?:fetch|request|axios|urllib|http\.get|http\.post|\.open\()', evidence):
                return False, "url_string_assignment"

        # Filter out docstrings / triple-quoted strings containing http://
        if re.search(r'(?:"""|\'\'\')', evidence):
            return False, "docstring_with_url"

        # Filter out string literals that are clearly documentation/help text
        # (long natural language strings with http:// in them)
        if re.search(r'(?:format|normalise|normalize|canonical|variant|convert|parse)\s.*http://', evidence, re.IGNORECASE):
            return False, "documentation_text_with_url"

        # Filter out security tool examples (nikto, nmap, etc.)
        if re.search(r'(?:nikto|nmap|burp|zap|sqlmap|metasploit|hydra)\s.*http://', evidence, re.IGNORECASE):
            return False, "security_tool_example"

        # Remaining http:// URLs to actual external services are real issues
        return True, "insecure_http_to_external"

    elif vid == "SESSION_ID_IN_URL":
        # Filter out README/documentation content
        if re.search(r'"(?:Readme|ReadmeCN|description)"', evidence, re.IGNORECASE):
            return False, "readme_content"

        # Filter out template placeholders
        if re.search(r'<UUID>|<session_id>|\{session_id\}|\$\{', evidence, re.IGNORECASE):
            return False, "template_placeholder"

        # Filter out comments
        if re.match(r'^\s*(?://|#|\*)', evidence):
            return False, "comment"

        # Filter out JSON data files
        if re.search(r'\.json$', filepath, re.IGNORECASE):
            return False, "json_data_file"

        # Filter out constructor/function calls where session_id is just a parameter
        # e.g.: McpSession(endpoint_url=..., session_id=session_id) — not a URL
        if re.search(r'(?:\w+\s*\(|new\s+\w+\s*\().*session_id\s*=', evidence) and not re.search(r'\?.*session_id=', evidence):
            return False, "constructor_parameter"

        # Filter out test files
        if re.search(r'(?:test|spec|mock|fixture|conftest|/tests?/)', filepath, re.IGNORECASE):
            return False, "test_file"

        # Actual session ID in URL construction (query string)
        if re.search(r'\?.*(?:sessionId|session_id|sid)=', evidence):
            return True, "session_id_in_url_construction"

        # session_id appended to URL path
        if re.search(r'(?:url|path|endpoint|route).*(?:sessionId|session_id|sid)=\$?\{?\w', evidence):
            return True, "session_id_in_url_construction"

        return False, "no_real_session_leak"

    return False, "unknown_id"


# ═══════════════════════════════════════════════════════════════════════════
#  CATEGORY 5: INPUT-VALIDATION
# ═══════════════════════════════════════════════════════════════════════════

def filter_input_validation_finding(finding: dict) -> tuple[bool, str]:
    """Filter input validation findings."""
    vid = finding.get("id", "")
    evidence = finding.get("evidence", "") or ""
    filepath = finding.get("file", "") or ""

    if vid == "COMMAND_INJECTION_RISK":
        # mcp-watch requires exec/spawn + user input keyword on same line
        # But "user", "input", "body", "params" appear in many safe contexts

        # Filter out third-party / vendored code (not the server's own code)
        if re.search(r'(?:node_modules|venv|\.venv|site-packages|vendor|dist|build|__pycache__|pip/_vendor)', filepath, re.IGNORECASE):
            return False, "third_party_code"

        # Filter out test files
        if re.search(r'(?:test|spec|mock|fixture|__test__|\.test\.|\.spec\.|/tests?/)', filepath, re.IGNORECASE):
            return False, "test_file"

        # Filter out regex.exec() — not command execution!
        # Includes /pattern/.exec(str) and named regex vars
        if re.search(r'\.exec\s*\(', evidence) and (
            re.search(r'(?:regex|Regex|RegExp|linkRegex|pattern|match)', evidence) or
            re.search(r'/[^/]+/\w*\.exec\s*\(', evidence)  # /pattern/.exec(str)
        ):
            return False, "regex_exec_not_command"

        # Filter out SQL/DB exec (not OS command injection, different vuln class)
        if re.search(r'(?:sql|SQL|\.exec\s*\(\s*["\'](?:SELECT|INSERT|UPDATE|DELETE|CREATE|DROP|ALTER))', evidence, re.IGNORECASE):
            return False, "sql_exec_not_command_injection"

        # Filter out DB/ORM .exec() — database query execution, not OS command
        if re.search(r'(?:query|statement|prepared|cursor|db|database|connection|conn|knex|sequelize|prisma|typeorm)\s*\.\s*exec', evidence, re.IGNORECASE):
            return False, "db_exec_not_command_injection"

        # Filter out CSS/style files — no command injection risk
        if re.search(r'\.(?:css|scss|sass|less)$', filepath, re.IGNORECASE):
            return False, "css_file"

        # Filter out description text and prompt examples (not actual code)
        if re.search(r'"description"', evidence, re.IGNORECASE):
            return False, "description_text"

        # Filter out example/documentation text (e.g. "if reviewer says 'change exec(userInput)'")
        if re.search(r'(?:example|e\.g\.|i\.e\.|says\s+"|change\s+`|reviewer|comment)', evidence, re.IGNORECASE):
            return False, "example_text"

        # Filter out prompt template strings
        if re.search(r'\.(?:ts|js)$', filepath) and re.search(r'(?:Example\s*-|`exec\()', evidence):
            return False, "prompt_template_text"

        # Filter out standard launcher scripts (spawn('node', [...process.argv]))
        # These pass through CLI args, not network user input
        if re.search(r'spawn\s*\(\s*["\']node["\']', evidence) and re.search(r'process\.argv', evidence):
            return False, "node_launcher_script"

        # Filter out rule description text / documentation strings (not actual code)
        if re.search(r'(?:Shell execution|Avoid\s+`|prefer\s+argument|strict\s+allowlist)', evidence, re.IGNORECASE):
            return False, "rule_description_text"

        # Filter out logger/monitoring methods that happen to have 'input' keyword nearby
        if re.search(r'(?:logger|log|monitor|analyze|report)\.\w+\s*\(', evidence, re.IGNORECASE):
            return False, "logging_not_execution"

        # Keep if it's genuinely exec/spawn with user-controlled input
        has_dangerous_exec = bool(re.search(
            r'(?:child_process|execSync|\bexec\b|spawn|\bsystem\b(?!\w)|popen|shell_exec|passthru)\s*\(',
            evidence
        ))
        has_user_input = bool(re.search(
            r'(?:req\.|params\.|query\.|body\.|input\.|args\.|user\w*Input)',
            evidence
        ))

        # argv is from process itself, not from network — lower risk
        has_only_argv = bool(re.search(r'argv', evidence)) and not has_user_input

        if has_dangerous_exec and has_user_input:
            return True, "command_injection_confirmed"

        if has_only_argv:
            return False, "process_argv_not_network_input"

        return False, "not_command_injection"

    elif vid == "SSRF_VULNERABILITY":
        # mcp-watch requires fetch/axios immediately followed by user input
        # This is already quite specific, but filter test/vendor files
        if re.search(r'(?:test|spec|mock|fixture|/tests?/)', filepath, re.IGNORECASE):
            return False, "test_file"
        if re.search(r'(?:node_modules|venv|\.venv|site-packages|vendor)', filepath, re.IGNORECASE):
            return False, "third_party_code"

        # Filter out database connection.fetch() — PostgreSQL asyncpg, not HTTP fetch
        if re.search(r'(?:connection|conn|pool|db|database|client|cursor)\s*\.\s*fetch', evidence, re.IGNORECASE):
            return False, "database_fetch_not_http"

        # Filter out ORM/DB query methods that look like fetch
        if re.search(r'(?:\.fetchone|\.fetchall|\.fetchmany|\.fetchval|\.fetchrow)\s*\(', evidence, re.IGNORECASE):
            return False, "database_fetch_method"

        # Filter out SDK/API .fetch() — Discord messages.fetch(), guild.stickers.fetch(), etc.
        if re.search(r'(?:messages?|channels?|guilds?|members?|users?|roles?|emojis?|reactions?|threads?|webhooks?|stickers?|bans?|invites?|pins?)\s*\.\s*fetch\s*\(', evidence, re.IGNORECASE):
            return False, "sdk_api_fetch_method"

        # Filter out any chained .something.fetch() on SDK objects (generic SDK pattern)
        if re.search(r'\.\w+\.\s*fetch\s*\(\s*(?:params|args|options|id|name)\b', evidence, re.IGNORECASE):
            return False, "sdk_chained_fetch"

        # Filter out CSS files — no SSRF from stylesheets
        if re.search(r'\.(?:css|scss|sass|less)$', filepath, re.IGNORECASE):
            return False, "css_file"

        # Filter out logger/monitor methods that happen to have 'request' and URL keywords
        if re.search(r'(?:logger|log)\.\w*(?:request|info|debug|warn)\s*\(', evidence, re.IGNORECASE):
            return False, "logging_not_fetch"

        # Filter out SDK client .request() — not direct HTTP fetch
        # e.g.: client.aiGateway.logs.request(), client.items.request()
        if re.search(r'(?:client|sdk|api|service)\.\w+(?:\.\w+)*\.request\s*\(', evidence, re.IGNORECASE):
            return False, "sdk_client_request"

        return True, "ssrf_pattern_confirmed"

    elif vid == "PATH_TRAVERSAL":
        # MASSIVE false positive source — matches any "../" including imports
        # Only keep if it's in a file read context with user input

        # Filter out import statements
        if re.search(r'(?:import|require|from)\s', evidence):
            return False, "import_statement"

        # Filter out relative path in string that's clearly a module reference
        if re.search(r'["\']\.\./', evidence) and re.search(r'(?:utils|lib|src|components|helpers|modules|services|config|types|interfaces)', evidence):
            return False, "module_relative_path"

        # Filter out comments
        if re.match(r'^\s*(?://|#|\*)', evidence):
            return False, "comment"

        # Filter out test files
        if re.search(r'(?:test|spec|mock|fixture)', filepath, re.IGNORECASE):
            return False, "test_file"

        # path.join with __dirname or __file__ and .. is static directory navigation
        if re.search(r'(?:path\.join|os\.path\.join)\s*\([^)]*(?:__dirname|__file__|os\.path\.dirname)', evidence):
            return False, "dirname_relative_navigation"

        # Keep only if there's a file operation with user-influenced path
        has_file_op = bool(re.search(r'(?:readFile|readdir|open|createReadStream|fs\.|path\.join)', evidence))
        has_user_input = bool(re.search(r'(?:req\.|params\.|query\.|body\.|input\.|args\.)', evidence))

        if has_file_op and has_user_input:
            return True, "path_traversal_with_user_input"

        return False, "static_relative_path"

    return False, "unknown_id"


# ═══════════════════════════════════════════════════════════════════════════
#  MAIN FILTER DISPATCHER
# ═══════════════════════════════════════════════════════════════════════════

CATEGORY_FILTERS = {
    "credential-leak": filter_credential_finding,
    "steganographic-attack": filter_steganographic_finding,
    "data-exfiltration": filter_data_exfiltration_finding,
    "protocol-violation": filter_protocol_violation_finding,
    "input-validation": filter_input_validation_finding,
}


def process_category(base_dir: Path, category: str, filter_fn) -> dict:
    """Process all JSON files in a category directory."""
    cat_dir = base_dir / category
    if not cat_dir.exists():
        print(f"  [SKIP] {category}/ not found")
        return {}

    json_files = sorted(cat_dir.glob("*.json"))
    if not json_files:
        print(f"  [SKIP] No JSON files in {category}/")
        return {}

    all_kept = []
    all_rejected = []
    stats_by_id = defaultdict(lambda: {"original": 0, "kept": 0, "rejected": 0, "reject_reasons": Counter()})
    total_original = 0
    total_kept = 0

    for json_file in json_files:
        # Skip existing filtered files
        if "filtered" in json_file.name or "refilter" in json_file.name:
            continue

        print(f"  Processing {json_file.name}...")

        with open(json_file, "r", encoding="utf-8") as f:
            data = json.load(f)

        findings = data.get("findings", [])
        severity = data.get("severity", "unknown")

        for finding in findings:
            if not is_valid_finding(finding):
                stats_by_id["_INVALID_ID"]["rejected"] += 1
                continue

            vid = finding["id"]
            stats_by_id[vid]["original"] += 1
            total_original += 1

            keep, reason = filter_fn(finding)

            if keep:
                finding["filter_confidence"] = reason
                all_kept.append(finding)
                stats_by_id[vid]["kept"] += 1
                total_kept += 1
            else:
                stats_by_id[vid]["rejected"] += 1
                stats_by_id[vid]["reject_reasons"][reason] += 1
                all_rejected.append({
                    "id": vid,
                    "reason": reason,
                    "evidence_preview": (finding.get("evidence", "") or "")[:80],
                    "server_name": finding.get("server_name", ""),
                })

    # Write filtered output
    filtered_dir = cat_dir / "filtered"
    filtered_dir.mkdir(exist_ok=True)

    output_file = filtered_dir / f"{category.replace('-', '_')}_filtered.json"
    output_data = {
        "category": category,
        "filter": "high_confidence_only",
        "filtered_at": datetime.now(timezone.utc).isoformat(),
        "original_total": total_original,
        "kept_total": total_kept,
        "rejection_rate": f"{((total_original - total_kept) / total_original * 100) if total_original > 0 else 0:.1f}%",
        "findings": all_kept,
    }

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(output_data, f, indent=4, ensure_ascii=False)

    # Write stats
    stats_file = filtered_dir / f"{category.replace('-', '_')}_filter_stats.json"
    stats_data = {
        "category": category,
        "filtered_at": datetime.now(timezone.utc).isoformat(),
        "totals": {
            "original": total_original,
            "kept": total_kept,
            "rejected": total_original - total_kept,
            "rejection_rate": f"{((total_original - total_kept) / total_original * 100) if total_original > 0 else 0:.1f}%",
        },
        "by_vulnerability_id": {
            vid: {
                "original": info["original"],
                "kept": info["kept"],
                "rejected": info["rejected"],
                "rejection_rate": f"{(info['rejected'] / info['original'] * 100) if info['original'] > 0 else 0:.1f}%",
                "top_reject_reasons": dict(info["reject_reasons"].most_common(10)),
            }
            for vid, info in sorted(stats_by_id.items())
        },
    }

    with open(stats_file, "w", encoding="utf-8") as f:
        json.dump(stats_data, f, indent=4, ensure_ascii=False)

    print(f"    -> {total_kept:,} kept / {total_original:,} original ({output_data['rejection_rate']} rejected)")
    print(f"    -> Saved to {output_file.name}")

    return {
        "category": category,
        "original": total_original,
        "kept": total_kept,
        "rejected": total_original - total_kept,
    }


# ═══════════════════════════════════════════════════════════════════════════
#  MAIN
# ═══════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description="Filter mcp-watch findings to high-confidence only")
    parser.add_argument("--input", "-i", type=Path, default=DEFAULT_BASE,
                        help="Base directory with category subdirectories")
    args = parser.parse_args()

    base_dir = args.input
    print(f"=" * 70)
    print(f"MCP-Watch High-Confidence Filter")
    print(f"Base directory: {base_dir}")
    print(f"=" * 70)

    global_stats = []

    for category, filter_fn in CATEGORY_FILTERS.items():
        print(f"\n{'─' * 50}")
        print(f"Category: {category}")
        print(f"{'─' * 50}")
        result = process_category(base_dir, category, filter_fn)
        if result:
            global_stats.append(result)

    # Write global summary
    print(f"\n{'=' * 70}")
    print(f"GLOBAL SUMMARY")
    print(f"{'=' * 70}")

    grand_original = sum(s["original"] for s in global_stats)
    grand_kept = sum(s["kept"] for s in global_stats)
    grand_rejected = grand_original - grand_kept

    summary = {
        "filter_run": datetime.now(timezone.utc).isoformat(),
        "grand_totals": {
            "original_findings": grand_original,
            "kept_findings": grand_kept,
            "rejected_findings": grand_rejected,
            "global_rejection_rate": f"{(grand_rejected / grand_original * 100) if grand_original > 0 else 0:.1f}%",
        },
        "per_category": global_stats,
    }

    summary_file = base_dir / "filter_global_summary.json"
    with open(summary_file, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False)

    for s in global_stats:
        rej_pct = (s["rejected"] / s["original"] * 100) if s["original"] > 0 else 0
        print(f"  {s['category']:30s}  {s['kept']:>8,} kept / {s['original']:>10,} original  ({rej_pct:.1f}% rejected)")

    print(f"\n  {'TOTAL':30s}  {grand_kept:>8,} kept / {grand_original:>10,} original  "
          f"({(grand_rejected / grand_original * 100) if grand_original > 0 else 0:.1f}% rejected)")
    print(f"\n  Summary saved to: {summary_file}")


if __name__ == "__main__":
    main()
